#include <iostream>
#include <stdexcept>
using namespace std;
// Definici贸n de la excepci贸n personalizada
class MiExcepcion : public exception {
public:
    const char* what() const noexcept override {
        return "Ha ocurrido un error personalizado";
    }
};

// Funci贸n que puede lanzar la excepci贸n personalizada
void funcionConExcepcion(bool lanzarExcepcion) {
    if (lanzarExcepcion) {
        throw MiExcepcion();
    } else {
        cout << "La funcion se ejecuto correctamente." << endl;
    }
}